
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimerFrame.java
 *
 * Created on 23-Oct-2012, 14:26:18
 */

/**
 *
 * @author w1389813
 */
public class TimerFrame extends javax.swing.JFrame {

    /** Creates new form TimerFrame */
    public TimerFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitValue = new javax.swing.JTextField();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        textField3 = new javax.swing.JTextField();
        textField4 = new javax.swing.JTextField();
        textField5 = new javax.swing.JTextField();
        textField6 = new javax.swing.JTextField();
        textField7 = new javax.swing.JTextField();
        showDigit = new javax.swing.JButton();
        addOne = new javax.swing.JButton();
        oneSecsDisplay = new javax.swing.JButton();
        oneSecs = new javax.swing.JTextField();
        showOneSecs = new javax.swing.JButton();
        tenSecsDisplay = new javax.swing.JButton();
        tenSecs = new javax.swing.JTextField();
        showTenSecs = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        startTimer = new javax.swing.JButton();
        minutesDisplay = new javax.swing.JButton();
        minutes = new javax.swing.JTextField();
        showMinutes = new javax.swing.JButton();
        tenMinutesDisplay = new javax.swing.JButton();
        tenMinutes = new javax.swing.JTextField();
        showTenMinutes = new javax.swing.JButton();
        hoursDisplay = new javax.swing.JButton();
        showHours = new javax.swing.JButton();
        hours = new javax.swing.JTextField();
        tenHoursDisplay = new javax.swing.JButton();
        tenHours = new javax.swing.JTextField();
        showTenHours = new javax.swing.JButton();
        minuteStop = new javax.swing.JTextField();
        secondStop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenMinuteStop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenSecondStop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hourStop = new javax.swing.JTextField();
        tenHourStop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Timer");

        digitValue.setText("000");
        digitValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitValueActionPerformed(evt);
            }
        });

        textField1.setBackground(new java.awt.Color(0, 0, 255));
        textField1.setText("    ");

        textField2.setBackground(new java.awt.Color(0, 0, 255));
        textField2.setText("      ");

        textField3.setBackground(new java.awt.Color(0, 0, 255));
        textField3.setText("      ");

        textField4.setBackground(new java.awt.Color(0, 0, 255));
        textField4.setText("     ");

        textField5.setBackground(new java.awt.Color(0, 0, 255));
        textField5.setText("      ");

        textField6.setBackground(new java.awt.Color(0, 0, 255));
        textField6.setText("     ");

        textField7.setBackground(new java.awt.Color(0, 0, 255));
        textField7.setText("      ");

        showDigit.setText("show the digit");
        showDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDigitActionPerformed(evt);
            }
        });

        addOne.setText("Add One");
        addOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneActionPerformed(evt);
            }
        });

        oneSecsDisplay.setText("OneSecs");
        oneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplayActionPerformed(evt);
            }
        });

        oneSecs.setText("0");
        oneSecs.setToolTipText("");
        oneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsActionPerformed(evt);
            }
        });

        showOneSecs.setText("showOneSecs");
        showOneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecsActionPerformed(evt);
            }
        });

        tenSecsDisplay.setText("TenSecs");
        tenSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecsDisplayActionPerformed(evt);
            }
        });

        tenSecs.setText("0");
        tenSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecsActionPerformed(evt);
            }
        });

        showTenSecs.setText("showTenSecs");
        showTenSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenSecsActionPerformed(evt);
            }
        });

        stop.setText("End Timer");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        startTimer.setText("Start Timer");
        startTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimerActionPerformed(evt);
            }
        });

        minutesDisplay.setText("Minutes");

        minutes.setText("0");

        showMinutes.setText("showMinutes");
        showMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMinutesActionPerformed(evt);
            }
        });

        tenMinutesDisplay.setText("TenMinutes");

        tenMinutes.setText("0");

        showTenMinutes.setText("showTenMinutes");
        showTenMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenMinutesActionPerformed(evt);
            }
        });

        hoursDisplay.setText("Hours");

        showHours.setText("showHours");
        showHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHoursActionPerformed(evt);
            }
        });

        hours.setText("0");

        tenHoursDisplay.setText("tenHours");

        tenHours.setText("0");

        showTenHours.setText("showTenHours");
        showTenHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenHoursActionPerformed(evt);
            }
        });

        jLabel1.setText("Minutes to stop at");

        jLabel2.setText("Seconds to stop at");

        jLabel3.setText("Ten Minutes to stop at");

        jLabel4.setText("Ten Seconds to stop at");

        tenHourStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenHourStopActionPerformed(evt);
            }
        });

        jLabel5.setText("Hours to stop at");

        jLabel6.setText("Ten Hours to stop at");

        jTextField2.setText("Press Enter in box to show time");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText(":");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(115, 115, 115)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel6)
                            .add(showTenHours)
                            .add(tenHours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tenHoursDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tenHourStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, hoursDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, hours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, showHours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, hourStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tenMinutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(showTenMinutes)
                            .add(jLabel3)
                            .add(tenMinuteStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(tenMinutesDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(showMinutes)
                            .add(minutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(minutesDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(minuteStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, tenSecsDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, tenSecs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, showTenSecs)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, tenSecondStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(textField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(oneSecsDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(oneSecs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(showOneSecs)
                            .add(jLabel2)
                            .add(secondStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(124, 124, 124)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(textField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(textField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(textField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(87, 87, 87)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, digitValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(layout.createSequentialGroup()
                                                .add(69, 69, 69)
                                                .add(showDigit)))
                                        .add(24, 24, 24))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(textField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(textField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(48, 48, 48)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(addOne)
                                            .add(startTimer)
                                            .add(stop))
                                        .add(38, 38, 38)))))))
                .add(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(136, 136, 136)
                        .add(textField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61))
                    .add(layout.createSequentialGroup()
                        .add(119, 133, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(digitValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(textField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(textField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(showDigit)
                            .add(textField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(addOne)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                                .add(startTimer))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(textField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(textField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(18, 18, 18)
                        .add(stop)
                        .add(39, 39, 39)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(oneSecsDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenSecsDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(minutesDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenMinutesDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(hoursDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenHoursDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(oneSecs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenSecs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(minutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenMinutes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(hours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tenHours, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(showTenSecs)
                        .add(showOneSecs)
                        .add(showMinutes))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(showTenMinutes)
                        .add(showHours)
                        .add(showTenHours)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(secondStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tenSecondStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(minuteStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tenMinuteStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(hourStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel4)
                                .add(jLabel1))
                            .add(jLabel3)
                            .add(jLabel5)))
                    .add(layout.createSequentialGroup()
                        .add(tenHourStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)))
                .add(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDigitActionPerformed
        int digit = Integer.parseInt(digitValue.getText());

        if ((digit == 0) || (digit > 9))
        {
            textField1.setVisible(true);
            textField2.setVisible(true);
            textField3.setVisible(true);
            textField4.setVisible(false); //not shown
            textField5.setVisible(true);
            textField6.setVisible(true);
            textField7.setVisible(true);
        }
        
        if (digit == 1)
        {
            textField1.setVisible(false);
            textField2.setVisible(false);
            textField3.setVisible(true);
            textField4.setVisible(false); 
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(false);
        }
        
        if (digit == 2)
        {
            textField1.setVisible(true);
            textField2.setVisible(false);
            textField3.setVisible(true);
            textField4.setVisible(true);
            textField5.setVisible(true);
            textField6.setVisible(false);
            textField7.setVisible(true);
        }
        
        if (digit == 3)
        {
            textField1.setVisible(true);
            textField2.setVisible(false);
            textField3.setVisible(true);
            textField4.setVisible(true);
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(true);
        }
        
        if (digit == 4)
        {
            textField1.setVisible(false);
            textField2.setVisible(true);
            textField3.setVisible(true);
            textField4.setVisible(true);
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(false);
        }
        
        if (digit == 5)
        {
            textField1.setVisible(true);
            textField2.setVisible(true);
            textField3.setVisible(false);
            textField4.setVisible(true);
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(true);
        }
        
        if (digit == 6)
        {
            textField1.setVisible(true);
            textField2.setVisible(true);
            textField3.setVisible(false);
            textField4.setVisible(true);
            textField5.setVisible(true);
            textField6.setVisible(true);
            textField7.setVisible(true);
        }
        
        if (digit == 7)
        {
            textField1.setVisible(true);
            textField2.setVisible(false);
            textField3.setVisible(true);
            textField4.setVisible(false);
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(false);
        }
        
        if (digit == 8)
        {
            textField1.setVisible(true);
            textField2.setVisible(true);
            textField3.setVisible(true);
            textField4.setVisible(true);
            textField5.setVisible(true);
            textField6.setVisible(true);
            textField7.setVisible(true);
        }
        
        if (digit == 9)
        {
            textField1.setVisible(true);
            textField2.setVisible(true);
            textField3.setVisible(true);
            textField4.setVisible(true);
            textField5.setVisible(false);
            textField6.setVisible(true);
            textField7.setVisible(false);
        }

       
    }//GEN-LAST:event_showDigitActionPerformed

    private void digitValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitValueActionPerformed

    private void addOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneActionPerformed
        int x = Integer.parseInt(digitValue.getText());
        //read digitValue and convert to integer then store in variable x
        int oneSec = Integer.parseInt(oneSecs.getText());
        int tenSec = Integer.parseInt(tenSecs.getText());
        int minute = Integer.parseInt(minutes.getText());
        int tenMinute = Integer.parseInt(tenMinutes.getText());
        int hour = Integer.parseInt(hours.getText());
        int tenHour = Integer.parseInt(tenHours.getText());
        int stopSecond = Integer.parseInt(secondStop.getText());
        int stopTenSecond = Integer.parseInt(tenSecondStop.getText());
        int stopMinute = Integer.parseInt(minuteStop.getText());
        int stopTenMinute = Integer.parseInt(tenMinuteStop.getText());
        int stopHour = Integer.parseInt(hourStop.getText());
        int stopTenHour = Integer.parseInt(tenHourStop.getText());
        
        x = x + 1;
        
        if (x > 9)
        {
            x = 0;
            oneSec = oneSec + 1;
            
            if (oneSec > 9)
            { 
              oneSec = 0; 
              tenSec = tenSec + 1;
            }
                if (tenSec > 5)
                {
                    tenSec = 0;
                    minute = minute + 1;
                }
                    if (minute > 9)
                    {
                        minute = 0;
                        tenMinute = tenMinute + 1;
                    }
                        if (tenMinute > 5)
                        {
                            tenMinute = 0;
                            hour = hour + 1;
                        }
                            if (hour > 9)
                            {
                                hour = 0;
                                tenHour = tenHour + 1;
                            }
                                if (tenHour == 2 && hour > 3)
                                {
                                    tenHour = 0;
                                    hour = 0; //when timer reaches 24:00 timer resets to 0
                                }              
        }
        if (oneSec == stopSecond && tenSec == stopTenSecond &&
                minute == stopMinute && tenMinute == stopTenMinute && 
                hour == stopHour && tenHour == stopTenHour)
        {
              this.dispose();
              System.exit(0); //stops program when the variables are equivilent
        }
          
        String ss = Integer.toString(x);
        digitValue.setText(ss);//set value into digitValue variable
        showDigitActionPerformed(evt);
        
        String dd = Integer.toString(oneSec);
        oneSecs.setText(dd); //set value into oneSecs variable
        showOneSecsActionPerformed(evt);     
        
        String cc = Integer.toString(tenSec);
        tenSecs.setText(cc);//set value into tenSecs variable
        showTenSecsActionPerformed(evt);
        
        String mm = Integer.toString (minute);
        minutes.setText(mm);//set value into minutes variable
        showMinutesActionPerformed(evt);
        
        String tt = Integer.toString (tenMinute);
        tenMinutes.setText(tt);//set value into tenMinutes variable
        showTenMinutesActionPerformed(evt);
        
        String hh = Integer.toString (hour);
        hours.setText(hh);//set value into hours variable
        showHoursActionPerformed(evt);
        String aa = Integer.toString (tenHour);
        tenHours.setText(aa);//set value into hours variable
        showTenHoursActionPerformed(evt);
    }//GEN-LAST:event_addOneActionPerformed

    private void oneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_oneSecsDisplayActionPerformed

    private void showOneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecsActionPerformed
        // TODO add your handling code here:
        int ones = Integer.parseInt(oneSecs.getText());
        if ((ones == 0) || (ones > 9))
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (ones == 1)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (ones == 2)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (ones == 3)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (ones == 4)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (ones == 5)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (ones == 6)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (ones == 7)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (ones == 8)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (ones == 9)
        {
           oneSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showOneSecsActionPerformed

    private void showTenSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenSecsActionPerformed
        // TODO add your handling code here:
        int tens = Integer.parseInt(tenSecs.getText());
        if (tens == 0)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (tens == 1)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (tens == 2)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (tens == 3)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (tens == 4)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (tens == 5)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (tens == 6)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (tens == 7)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (tens == 8)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (tens == 9)
        {
           tenSecsDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showTenSecsActionPerformed

    private void tenSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSecsActionPerformed

    private void oneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_oneSecsActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_stopActionPerformed

    private void startTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimerActionPerformed
        javax.swing.Timer tm = new javax.swing.Timer(100, new ActionListener() {
    public void actionPerformed(ActionEvent evt)  { 
        addOneActionPerformed(evt);
    }
        }); 
        tm.start();
    }//GEN-LAST:event_startTimerActionPerformed

    private void tenSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSecsDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSecsDisplayActionPerformed

    private void showMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMinutesActionPerformed
        int minute = Integer.parseInt(minutes.getText());
        if (minute == 0)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (minute == 1)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (minute == 2)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (minute == 3)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (minute == 4)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (minute == 5)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (minute == 6)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (minute == 7)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (minute == 8)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (minute == 9)
        {
           minutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showMinutesActionPerformed

    private void showTenMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenMinutesActionPerformed
        int tenMinute = Integer.parseInt(tenMinutes.getText());
        if (tenMinute == 0)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (tenMinute == 1)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (tenMinute == 2)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (tenMinute == 3)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (tenMinute == 4)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (tenMinute == 5)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (tenMinute == 6)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (tenMinute == 7)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (tenMinute == 8)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (tenMinute == 9)
        {
           tenMinutesDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showTenMinutesActionPerformed

    private void showHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHoursActionPerformed
        int hour = Integer.parseInt(hours.getText());
        if (hour == 0)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (hour == 1)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (hour == 2)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (hour == 3)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (hour == 4)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (hour == 5)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (hour == 6)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (hour == 7)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (hour == 8)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (hour == 9)
        {
           hoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showHoursActionPerformed

    private void showTenHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenHoursActionPerformed
        int tenHour = Integer.parseInt(tenHours.getText());
        if (tenHour == 0)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number0.jpg"
                ));
        }
        if (tenHour == 1)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 1.jpg"
           ));
        }
        if (tenHour == 2)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number2.jpg"
                ));
        }
        if (tenHour == 3)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 3.jpg"
                ));
        }
        if (tenHour == 4)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 4.jpg"
                ));
        }
        if (tenHour == 5)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 5.jpg"
                ));
        }
        if (tenHour == 6)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 6.jpg"
                ));
        }
        if (tenHour == 7)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 7.jpg"
                ));
        }
        if (tenHour == 8)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 8.jpg"
                ));
        }
        if (tenHour == 9)
        {
           tenHoursDisplay.setIcon(new
           javax.swing.ImageIcon("C:\\Users\\Starrk\\"
           + "Documents\\NetBeansProjects\\Digital timer project\\number 9.jpg"
                ));
        }
    }//GEN-LAST:event_showTenHoursActionPerformed

    private void tenHourStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenHourStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenHourStopActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
        Date time = new Date();
        dateFormat.format(time);
        jTextField2.setText(dateFormat.format(time));
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOne;
    private javax.swing.JTextField digitValue;
    private javax.swing.JTextField hourStop;
    private javax.swing.JTextField hours;
    private javax.swing.JButton hoursDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField minuteStop;
    private javax.swing.JTextField minutes;
    private javax.swing.JButton minutesDisplay;
    private javax.swing.JTextField oneSecs;
    private javax.swing.JButton oneSecsDisplay;
    private javax.swing.JTextField secondStop;
    private javax.swing.JButton showDigit;
    private javax.swing.JButton showHours;
    private javax.swing.JButton showMinutes;
    private javax.swing.JButton showOneSecs;
    private javax.swing.JButton showTenHours;
    private javax.swing.JButton showTenMinutes;
    private javax.swing.JButton showTenSecs;
    private javax.swing.JButton startTimer;
    private javax.swing.JButton stop;
    private javax.swing.JTextField tenHourStop;
    private javax.swing.JTextField tenHours;
    private javax.swing.JButton tenHoursDisplay;
    private javax.swing.JTextField tenMinuteStop;
    private javax.swing.JTextField tenMinutes;
    private javax.swing.JButton tenMinutesDisplay;
    private javax.swing.JTextField tenSecondStop;
    private javax.swing.JTextField tenSecs;
    private javax.swing.JButton tenSecsDisplay;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField textField3;
    private javax.swing.JTextField textField4;
    private javax.swing.JTextField textField5;
    private javax.swing.JTextField textField6;
    private javax.swing.JTextField textField7;
    // End of variables declaration//GEN-END:variables

}
